# [START cloudbuild]
steps:
# This step runs the unit tests on the app
- name: 'python:3.9-slim-buster'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install flask && pip install --upgrade google-cloud-firestore && python test_app.py -v'

# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/acg-resume-api:$SHORT_SHA'
  - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/acg-resume-api:$SHORT_SHA'

# This step pushes the image to Artifact Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-east4-docker.pkg.dev/$PROJECT_ID/acg-resume-api/acg-resume-api:latest', '.' ]
images:
  - 'us-east4-docker.pkg.dev/$PROJECT_ID/acg-resume-api/acg-resume-api:latest'
# [END cloudbuild]


# [START cloudbuild-trigger-cd]
# This step clones the hello-cloudbuild-env repository
- name: 'gcr.io/cloud-builders/gcloud'
  id: Clone env repository
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    gcloud source repos clone acg-resume-api-prod && \
    cd acg-resume-api-prod && \
    git checkout candidate && \
    git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)')
# This step pushes the manifest back to acg-resume-api-prod
- name: 'gcr.io/cloud-builders/gcloud'
  id: Push manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    cp api.py cloudbuild.yaml cloudbuild-delivery.yaml Dockerfile requirements.txt test_app.py acg-resume-api-prod/ && \
    cd acg-resume-api-prod && \
    git add . && \
    git commit -m "Deploying image gcr.io/${PROJECT_ID}/acg-resume-api:${SHORT_SHA}
    Built from commit ${COMMIT_SHA} of repository github_pbrady32_acg-resume-api
    Author: $(git log --format='%an <%ae>' -n 1 HEAD)" && \
    git push origin candidate
# [END cloudbuild-trigger-cd]