# [START cloudbuild]
steps:
# This step runs the unit tests on the app
- name: 'python:3.9-slim-buster'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install flask && pip install --upgrade google-cloud-firestore && python test_app.py -v'

# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/acg-resume-api:$SHORT_SHA'
  - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/acg-resume-api:$SHORT_SHA'
# [END cloudbuild]